#include "src/game/envfx_snow.h"

const GeoLayout fnab_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, fnab_dl_Plane_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, fnab_dl_Plane_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_ALPHA, fnab_dl_Plane_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, 2232, 64, -2371, fnab_dl_treeboard_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, 2249, 64, -2371, fnab_dl_treeboard_001_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, 2265, 64, -2371, fnab_dl_treeboard_002_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, 727, 44, -1114, fnab_dl_treeboard_003_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, 727, 44, -1014, fnab_dl_treeboard_004_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, 727, 44, -914, fnab_dl_treeboard_005_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, 727, 44, -814, fnab_dl_treeboard_006_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, 300, 92, -700, fnab_dl_treeboard_007_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, 300, 40, -1100, fnab_dl_treeboard_008_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, 300, 92, -300, fnab_dl_treeboard_009_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout fnab_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 4, 2500, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, fnab_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
